# Generated by Django 2.1.7 on 2019-03-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hash_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=256)),
                ('hashtag', models.CharField(default='None', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='tweet_by_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=256)),
                ('tweet_id', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='twitter_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=256)),
                ('text', models.CharField(max_length=1024)),
                ('reply_to_status', models.CharField(max_length=256)),
                ('reply_to_user_id', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
                ('retweet_count', models.IntegerField()),
                ('lang', models.CharField(max_length=256)),
                ('hashtag', models.BooleanField(default=False)),
                ('user_mentioned', models.BooleanField(default=False)),
                ('url', models.BooleanField(default=False)),
                ('created_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=256)),
                ('username', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=256)),
                ('screenname', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=1024)),
                ('followers_count', models.IntegerField()),
                ('friends_count', models.IntegerField()),
                ('status_count', models.IntegerField()),
                ('created_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='user_mentioned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=256)),
                ('mentioned', models.CharField(default='None', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='user_url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=256)),
                ('url', models.CharField(default='None', max_length=256)),
            ],
        ),
    ]
