# Generated by Django 2.1.7 on 2019-03-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitter_data',
            name='created_at',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='created_at',
            field=models.CharField(max_length=256),
        ),
    ]
