# Generated by Django 2.1.7 on 2019-04-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190326_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='hash_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=256)),
                ('hashclass', models.CharField(max_length=256)),
            ],
        ),
    ]
