# Generated by Django 2.1.7 on 2019-04-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_polarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='polarity',
            name='etime',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='polarity',
            name='stime',
            field=models.DateField(null=True),
        ),
    ]
