# Generated by Django 2.1.7 on 2019-04-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20190410_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polarity',
            name='etime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='polarity',
            name='stime',
            field=models.DateTimeField(null=True),
        ),
    ]
