# Generated by Django 2.1.7 on 2019-05-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_hash_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hash_count',
            name='hashtag',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
